---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pkgr24.io
  resources:
  - packages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkgr24.io
  resources:
  - packages/finalizers
  verbs:
  - update
- apiGroups:
  - pkgr24.io
  resources:
  - packages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pkgr24.io
  resources:
  - requirements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkgr24.io
  resources:
  - requirements/finalizers
  verbs:
  - update
- apiGroups:
  - pkgr24.io
  resources:
  - requirements/status
  verbs:
  - get
  - patch
  - update
