apiVersion: pkgr24.io/v1alpha1
kind: Package
metadata:
  name: nginz-stable
spec:
  install: false
  removalPolicy: cascade
  bundles:
    - version: 1.14.2
      repo: https://github.com/perdasilva/pkgr24-examples
    - version: 1.7.9
      repo: https://github.com/perdasilva/pkgr24-examples
