apiVersion: pkgr24.io/v1alpha1
kind: Package
metadata:
  name: openshift-special-resource-operator
spec:
  packageFBC: |
    {
        "schema": "olm.package",
        "name": "openshift-special-resource-operator",
        "defaultChannel": "stable"
    }
    {
        "schema": "olm.channel",
        "name": "4.11",
        "package": "openshift-special-resource-operator",
        "entries": [
            {
                "name": "openshift-special-resource-operator.4.11.0-202208031306",
                "skipRange": ">=4.6.0 <4.9.0"
            }
        ]
    }
    {
        "schema": "olm.channel",
        "name": "stable",
        "package": "openshift-special-resource-operator",
        "entries": [
            {
                "name": "openshift-special-resource-operator.4.11.0-202208031306",
                "skipRange": ">=4.6.0 <4.9.0"
            }
        ]
    }
    {
        "schema": "olm.bundle",
        "name": "openshift-special-resource-operator.4.11.0-202208031306",
        "package": "openshift-special-resource-operator",
        "image": "registry.redhat.io/openshift4/special-resource-operator-bundle@sha256:6d6fc1dbf62456fb4e3e9c04c1bf88b89ec8404a487869556ea9a9cc4cb0d093",
        "properties": [
            {
                "type": "olm.gvk",
                "value": {
                    "group": "sro.openshift.io",
                    "kind": "PreflightValidation",
                    "version": "v1beta1"
                }
            },
            {
                "type": "olm.gvk",
                "value": {
                    "group": "sro.openshift.io",
                    "kind": "SpecialResource",
                    "version": "v1beta1"
                }
            },
            {
                "type": "olm.gvk",
                "value": {
                    "group": "sro.openshift.io",
                    "kind": "SpecialResourceModule",
                    "version": "v1beta1"
                }
            },
            {
                "type": "olm.package",
                "value": {
                    "packageName": "openshift-special-resource-operator",
                    "version": "4.11.0-202208031306"
                }
            }
        ],
        "relatedImages": [
            {
                "name": "ose-kube-rbac-proxy",
                "image": "registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:7abede2caee5a935f87219f51732cff5a8c3bfca1eab1f0e9725ca93fd347b89"
            },
            {
                "name": "",
                "image": "registry.redhat.io/openshift4/special-resource-operator-bundle@sha256:6d6fc1dbf62456fb4e3e9c04c1bf88b89ec8404a487869556ea9a9cc4cb0d093"
            },
            {
                "name": "special-resource-rhel8-operator",
                "image": "registry.redhat.io/openshift4/special-resource-rhel8-operator@sha256:eb20f30254ca3abfa8efc5a94e84f7a28afae56847c9305362685de742cbd5ff"
            }
        ]
    }
